version: "3.9"

services:
  django:
    build: .
    command: ./django.sh
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - celery
    ports:
      - 8000:8000

  celery:
    build: .
    command: ./celery.sh
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  redis:
    image: redis

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
